### ISSUE TITLE
add clojisr ?

### ISSUE THREAD

**Issue by behrica** [scicloj/noj#1]
Maybe it's is the right moment to just "do it",
and declare the "Clojure data science stack".... and call it "noj"..

any reason you have left out "clojisr" ?

That would in my view as well be the "only missing piece",
specially due to "ggplot"

**Comment by daslu** [comment]
Thanks, @behrica, and sorry for my slow reply.

Sounds good.

I will look into it.

**Comment by daslu** [comment]
(resolved by @behrica at #3)
