### ISSUE TITLE
use `scicloj.ml` 0.3

### ISSUE THREAD

**Issue by behrica** [scicloj/noj#2]
scicloj/scicloj.ml {:mvn/version "0.3"} is now compatible with TMD 7.x

https://github.com/scicloj/noj/blob/397f0ad3390bb90c4164c75ebd0b4b4bfb5fe4de/deps.edn#L12

**Comment by daslu** [comment]
@behrica 
Thanks, yes, fantastic news.

**Comment by daslu** [comment]
fixed in 80d39dc6efb47e9d3919a257bed27bb564ab1da7 (version 1-alpha16)
