### ISSUE TITLE
move r^2 calculation to `metamorph.ml`

### ISSUE THREAD

**Issue by behrica** [scicloj/noj#20]
In here:

https://github.com/scicloj/metamorph.ml/blob/main/src/scicloj/metamorph/ml/loss.clj

It has other metrics alreday.

**Comment by daslu** [comment]
Good idea.

**Comment by behrica** [comment]
exists as well in fastmath:
https://generateme.github.io/fastmath/notebooks/notebooks/stats/#metrics

Is it the same ?

**Comment by daslu** [comment]
(closing as all functionality will have been moved out of Noj soon)
