### ISSUE TITLE
fastmath has histogram calculation as well

### ISSUE THREAD

**Issue by behrica** [scicloj/noj#21]
https://generateme.github.io/fastmath/notebooks/notebooks/stats/#histogram

Noj has an other one.
Are they the same , maybe just different in "return type". ?

**Comment by daslu** [comment]
In any case, it is a good idea to use the existing Fasthmath function.
Thanks for finding it.

**Comment by daslu** [comment]
https://github.com/scicloj/noj/commit/a19c2b3c90341182f20541d0cf960445c48bbcf9
