### ISSUE TITLE
fastmath has `correlation-matrix` as well 

### ISSUE THREAD

**Issue by behrica** [scicloj/noj#22]
https://generateme.github.io/fastmath/notebooks/notebooks/stats/#correlation

**Comment by daslu** [comment]
The Noj function `scicloj.noj.1.stats/calc-correlation-matrix` is a wrapper of `fastmath.stats/pearson-correlation` as a `tech.ml.dataset`.

I added it a as a draft at early stages of Noj. It was following a user request to serve some visualization needs. We experimented with various correlation heatmap plots on top of it. 

We never continued that project, so it is safe to remove it and the `round` function for now.

We can consider adding both if and when we come back to that project.
