### ISSUE TITLE
move docs generation to ci build

### ISSUE THREAD

**Issue by behrica** [scicloj/noj#33]
@daslu 
I can do that if you tell me what you do manly.

It needs a bit of GitHub action runner magic, as the runner need to commit the changes into "docs".
But I did that already ones, so can just copy it.

**Comment by daslu** [comment]
Thanks for looking into that.
What I do at the moment to render the docs is evaluate `notebooks/dev.clj`.

Let us think. 

As far as I understand, there are a few kinds of typical changes to this repo:
* updates to deps
* changes in worfklow (e.g., your recent additions to the test process)
* updates to docs (e.g., adding a tutorial, or just fixing a typo)
* other little details (e.g., changes to README, .gitignore)

The docs generation is now slow, and it will become smaller.
Do you think we should invoke it automatically in all cases?

**Comment by behrica** [comment]
I am absolutely convinced on automation via GitHub actions and therefore from scratch 
 This being slow isn't a problem for me.

**Comment by behrica** [comment]
GitHub offers caching to address if needed. 
But first automate,  then think about caching. 
My opinion,  at least.

**Comment by behrica** [comment]
It takes 7 minutes know and it does things double for sure.
Ones automated 'you' don't need to worry about   any manual task anymore. 
And we optimize the build in case we see it important.

**Comment by behrica** [comment]
The current failure should go away once its on 'main', I hope

**Comment by daslu** [comment]
Thanks for checking. 

> This being slow isn't a problem for me.

I think this is important. It will make it difficult to debug when things are broken, when different people collaborate, when a few branches are merged, etc.

> it does things double for sure.

If I understand correctly, we run the every namespace at least three times:
1. generating tests
2. testing
3. rendering tests
Probably, at least 1 and 3 can be the same run.

Also, we could probably make the automatic tutorial smaller and faster. But there will be more tutorials that will make things difficult.
Maybe this means that slow tutorials should have their own space (or move to `cloure-data-tutorials`).

**Comment by daslu** [comment]
Anyway, as you said, I think it makes sense to make it work (if that it not a big task for you) and then optimize later.

**Comment by daslu** [comment]
Interesting, I see the `clojure-data-tutorials` builds are very fast, even though they have a few projects to render.
https://github.com/scicloj/clojure-data-tutorials/actions
![image](https://github.com/user-attachments/assets/1c54269c-9c6f-4c43-b6e0-2c964d34977f)

**Comment by behrica** [comment]
But code debugging happens locally anyway.
Once the build works, PRs should only merged when they don't break the
build.

Daniel Slutsky ***@***.***> schrieb am Sa., 28. Sept. 2024,
18:01:

**Comment by behrica** [comment]
> Interesting, I see the `clojure-data-tutorials` builds are very fast, even though they have a few projects to render. 
These have know a condition, which only re-renders changed projects.

**Comment by behrica** [comment]
> > Interesting, I see the `clojure-data-tutorials` builds are very fast, even though they have a few projects to render.
 These have know a condition, which only re-renders changed projects.

**Comment by behrica** [comment]
But the tutorials are slow because each creates its own docker container, this is way slower then the "make!" of the project.
This is not happening here. The container creation happens only ones

**Comment by behrica** [comment]
> > > Interesting, I see the `clojure-data-tutorials` builds are very fast, even though they have a few projects to render.
> 
> These have know a condition, which only re-renders changed projects.



> > > Interesting, I see the `clojure-data-tutorials` builds are very fast, even though they have a few projects to render.
> 
> These have know a condition, which only re-renders changed projects.

Which has a problem, when some "globalls" get changed, as nothing is re-build.
-> From scratch is usually simpler, if not we needed to find a way to express dependencies...

**Comment by behrica** [comment]
I fixed the build of noj:
https://github.com/scicloj/noj/actions

**Comment by behrica** [comment]
The build  of my PR #34 is working as well :
https://github.com/behrica/noj/actions

If you want, you can merge it, it should keep working.
It is by far not optimized, we can do this lter, in my view

**Comment by daslu** [comment]
Nice, thanks, I'll comment on the PR.

**Comment by daslu** [comment]
fixed by #34
