### ISSUE TITLE
metamorph ml has as well toy datasets

### ISSUE THREAD

**Issue by behrica** [scicloj/noj#4]
https://github.com/scicloj/noj/blob/7a5688b0ed7a478befbc6854c651fa1518554377/src/scicloj/noj/v1/datasets.clj#L1

I propose to move your over to here
https://github.com/scicloj/metamorph.ml/blob/main/src/scicloj/metamorph/ml/toydata.clj
, if not existing.

**Comment by daslu** [comment]
Thanks, @behrica. You're right it probably makes sense to have them in one place, even if the approaches are a bit different. 

I'll look for a simple way to move without breaking existing tutorials, etc.

**Comment by behrica** [comment]
Maybe just copy them over.
And "deprecate" them in code via comment, and we should try to avoid to use them in future tutorials.

**Comment by daslu** [comment]
(removed the datasets namespace at #13)
