### ISSUE TITLE
unit tests do not test various clojure versions

### ISSUE THREAD

**Issue by behrica** [scicloj/noj#42]
The looping here https://github.com/scicloj/noj/blob/a3aee6f5e69637e1a6b06cfa7cf4f0e1b33b85d6/build.clj#L25

does nothing, as the aliases 
:1.11 :1.12 :master

do not exist in the deps.edn 

So it runs teh tests 4 times with default clojure version.

**Comment by daslu** [comment]
Oh, thanks!
