### ISSUE TITLE
possibly rename the prepare_for_ml tutorial title

### ISSUE THREAD

**Issue by daslu** [scicloj/noj#51]
@behrica Maybe you'll have an idea whether we should rename this chapter.

This tutorial is really so helpful for understanding the categorical variables, but people who are looking to learn on this topic find it difficult to find it.
https://scicloj.github.io/noj/noj_book.prepare_for_ml.html

**Comment by behrica** [comment]
With 'prepare' I mean to make the data numeric

**Comment by daslu** [comment]
@behrica I mostly mean the title
"#Machine learning specific functionality in `tech.ml.dataset`", which seems rather specific to the beginner user.

Maybe a shorter title that clarifies this is the intro to categorical columns would make this chapter more noticable.

**Comment by behrica** [comment]
fixed by 226a22fcababebbd7037ddd58c9083fc794f9a6c

**Comment by daslu** [comment]
Thanks
