### ISSUE TITLE
possible date parsing issue in Walmart store openings dataset

### ISSUE THREAD

**Issue by zuzhi** [scicloj/noj#55]
The Walmart store openings dataset used in the Plotly section in Datasets may have a minor issue with the date fields `:OPENDATE` and `:date_super`. When parsed, dates like "7/1/62" are interpreted as "2062-07-01" in Tablecloth.

https://github.com/scicloj/noj/blob/b03dc557426d2d764cfa5fb5e0cae5d0a4f5f5f2/notebooks/noj_book/datasets.clj#L35-L40

| :storenum |  :OPENDATE | :date_super | :conversion | :st | :county |            :STREETADDR |          :STRCITY | :STRSTATE | :ZIPCODE | :type_store |      :LAT |      :LON | :MONTH | :DAY | :YEAR |
|----------:|------------|-------------|------------:|----:|--------:|------------------------|-------------------|-----------|---------:|-------------|----------:|----------:|-------:|-----:|------:|
|         1 | 2062-07-01 |  2097-03-01 |           1 |   5 |       7 |       2110 WEST WALNUT |            Rogers |        AR |    72756 | Supercenter | 36.342235 | -94.07141 |      7 |    1 |  1962 |
|         2 | 2064-08-01 |  2096-03-01 |           1 |   5 |       9 |       1417 HWY 62/65 N |          Harrison |        AR |    72601 | Supercenter | 36.236984 | -93.09345 |      8 |    1 |  1964 |
|         4 | 2065-08-01 |  2002-03-01 |           1 |   5 |       7 |      2901 HWY 412 EAST |    Siloam Springs |        AR |    72761 | Supercenter | 36.179905 | -94.50208 |      8 |    1 |  1965 |
|         8 | 2067-10-01 |  2093-03-01 |           1 |   5 |      29 |  1621 NORTH BUSINESS 9 |         Morrilton |        AR |    72110 | Supercenter | 35.156491 | -92.75858 |     10 |    1 |  1967 |
|         7 | 2067-10-01 |             |             |   5 |     119 | 3801 CAMP ROBINSON RD. | North Little Rock |        AR |    72118 |    Wal-Mart | 34.813269 | -92.30229 |     10 |    1 |  1967 |

Since the dates are truncated to two digits, the year defaults to 20xx, resulting in misinterpreted dates.

While this may not necessarily qualify as an issue, given it’s the default behavior when handling two-digit years in this format, it could still cause confusion. 

For the purpose of the this section, which is to demonstrate the use of available Plotly datasets, we can simply replace this dataset with another from the Plotly dataset list to avoid this issue.

Alternatively, we can use Tablecloth to update the columns with the correct dates, given that the data spans from 1962 and 2006.

@daslu Should we replace the dataset, adjust the dates, or leave it as is? I’d appreciate your input on this. Thank you!

**Comment by daslu** [comment]
@zuzhi thanks for catching this!

I think it is a good idea to replace the dataset simply because date manipulation is not the purpose of that example.

Would you like to suggest a pull request?

**Comment by zuzhi** [comment]
Sure! I’ve submitted a pull request.
